server: 
  port: 8080
  servlet: 
    context-path: /test

spring: 
  datasource:
    username: root
    password: 528800
    url: jdbc:mysql://localhost:3306/netbar?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


mybatis:
  mapper-locations: classpath:/mapper/*.xml

